### ISSUE TITLE
Renaming user fields

### ISSUE THREAD

**Issue by manton** [microdotblog/snippets#7]
I think we should consider renaming a few fields to make things more consistent with the Micro.blog API (and JSON Feed). Specifically on `SnippetsUser`:

* userHandle → username
* pathToUserImage → avatarURL
* pathToWebSite → siteURL
* userImage → avatarImage

Thoughts @cheesemaker?

**Comment by cheesemaker** [comment]
I'm good with this change, except to be consistent, it will be userHandle -> userName.

**Comment by cheesemaker** [comment]
Changed/fixed

**Comment by manton** [comment]
Actually… 🙂 It really needs to be `username` all lowercase since it's a distinct word vs. something like `fullName`, which is 2 words. I know it sometimes doesn't seem consistent, but it's `username` everywhere: JSON Feed, the Micro.blog API, etc.

**Comment by cheesemaker** [comment]
Fixed on 1.0.1
